name: jupyter-mentor
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - nbdev=2.3.12
  - jupyterlab
  - jupyter-ai
  - python=3.11
  - tiktoken
  - langchain
  - ipywidgets
  - pandas
  - fastcore=1.5.28
  - jupyterlab
  - ipykernel
  - jupyter
  - voila
  - notebook
  - sortedcontainers
  - pip
  - pip:
    - langchain-openai
