# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupyter-mentor',
                'doc_host': 'https://Jupyter4Science.github.io',
                'git_url': 'https://github.com/Jupyter4Science/jupyter-mentor',
                'lib_path': 'jupyter_mentor'},
  'syms': {'jupyter_mentor.core': {'jupyter_mentor.core.foo': ('core.html#foo', 'jupyter_mentor/core.py')}}}
