# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_chatbot.ipynb.

# %% auto 0
__all__ = ['ChatBotModel', 'ChatBotView', 'ChatBot']

# %% ../nbs/04_chatbot.ipynb 1
import ipywidgets as widgets
import traitlets
from ipywidgets import Textarea, Text, Layout, HBox, Stack, Layout
from traitlets import HasTraits
import os
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_openai import ChatOpenAI
from .llm import FileModel

# %% ../nbs/04_chatbot.ipynb 2
class ChatBotModel(FileModel):

    def __init__(self, bot_template="You are playing the role of a tutor/educator", human_template="{input_text}"):
        super().__init__()
        self.human_template = human_template
        self.human_message_prompt = HumanMessagePromptTemplate.from_template(self.human_template)
        self.update_bot_template(bot_template)

    def update_bot_template(self, bot_template):
        self.bot_template = bot_template
        self.bot_message_prompt = SystemMessagePromptTemplate.from_template(self.bot_template)
        self.chat_prompt = ChatPromptTemplate.from_messages([self.bot_message_prompt, self.human_message_prompt])

    def update_human_template(self, human_template):
        self.human_template = human_template
        self.human_message_prompt = HumanMessagePromptTemplate.from_template(self.human_template)
        self.chat_prompt = ChatPromptTemplate.from_messages([self.bot_message_prompt, self.human_message_prompt])        

    def prompt(self, input_text):
        ret = self.llm.invoke(input_text)
        return ret.content
    
    def prompt_with_template(self, kwargs):
        ret = self.llm.invoke(self.chat_prompt.format_prompt(**kwargs))
        return ret.content

    def prompt_course_files(self, input_text, k = 4):
        if self.db:
            try:
                docs = self.db.similarity_search(input_text, k=1)
                docs_content = " ".join([d.page_content for d in docs])
                self.update_bot_template("You are an educator/tutor. Answer the question based on the following information: {docs}")
                ret = self.llm.invoke(self.chat_prompt.format_prompt(docs=docs, input_text=input_text)) 
                return "\n\n".join([ret.content + '\n\nSourced from ' + docs[0].metadata['source'] + ': \n', docs_content])
            except Exception as e: 
                return docs[0].page_content
        else:
            return self.prompt(input_text)

# %% ../nbs/04_chatbot.ipynb 6
class ChatBotView(widgets.VBox):
    
    def __init__(self):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()

        self.chat = Textarea(
            disabled = True,
            layout=Layout(width='90%', height='400px')
        )
        self.user_input_and_submit = HBox()
        self.user_input = widgets.Text(
            placeholder='Message AI chatbot...',
            #layout=Layout(width='100%')
        )
        self.submit_button = widgets.Button(
            value=False,
            disabled=False,
            button_style='success',
            icon='arrow-circle-right' 
        )
        self.user_input_and_submit.children = (self.user_input, self.submit_button)

        self.children = (self.chat, self.user_input_and_submit) 

# %% ../nbs/04_chatbot.ipynb 8
class ChatBot(ChatBotView):

    def __init__(self, model):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()
        self.submit_button.on_click(self.on_click)
        self.model =model

    def on_click(self, change):
        self.chat.value = self.chat.value + "USER: " + self.user_input.value + '\n\n'
        self.user_input.value = ''
        ret = self.model.prompt_course_files(self.user_input.value)
        self.chat.value = self.chat.value +  "CHATBOT: "  + ret + '\n\n'
