# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_chatbot.ipynb.

# %% auto 0
__all__ = ['ChatBotModel', 'ChatBotView', 'ChatBot', 'StudentChatBot', 'EducatorChatBot']

# %% ../nbs/06_chatbot.ipynb 1
import ipywidgets as widgets
import traitlets
from ipywidgets import Textarea, Text, Layout, HBox, Stack, Layout
from traitlets import HasTraits
import os
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_openai import ChatOpenAI

# %% ../nbs/06_chatbot.ipynb 5
class ChatBotModel(HasTraits):

    def __init__(self, llm, bot_template="You are playing the role of a tutor/educator", human_template="{input_text}"):
        super().__init__()
        self.llm = llm
        self.human_template = human_template
        self.human_message_prompt = HumanMessagePromptTemplate.from_template(self.human_template)
        self.update_bot_template(bot_template)

    def update_bot_template(self, bot_template):
        self.bot_template = bot_template
        self.bot_message_prompt = SystemMessagePromptTemplate.from_template(self.bot_template)
        self.chat_prompt = ChatPromptTemplate.from_messages([self.bot_message_prompt, self.human_message_prompt])

    def update_human_template(self, human_template):
        self.human_template = human_template
        self.human_message_prompt = HumanMessagePromptTemplate.from_template(self.human_template)
        self.chat_prompt = ChatPromptTemplate.from_messages([self.bot_message_prompt, self.human_message_prompt])        
        
    def prompt(self, kwargs):
        ret = self.llm.invoke(self.chat_prompt.format_prompt(**kwargs))
        #ret = self.llm.invoke(self.chat_prompt.format_prompt(input_text=input_text))
        return ret.content

# %% ../nbs/06_chatbot.ipynb 8
class ChatBotView(widgets.VBox):
    
    def __init__(self):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()

        self.chat = Textarea(
            disabled = True,
            layout=Layout(width='90%', height='400px')
        )
        self.user_input_and_submit = HBox()
        self.user_input = widgets.Text(
            placeholder='Message AI chatbot...',
            #layout=Layout(width='100%')
        )
        self.submit_button = widgets.Button(
            value=False,
            disabled=False,
            button_style='success',
            icon='arrow-circle-right' 
        )
        self.user_input_and_submit.children = (self.user_input, self.submit_button)

        self.children = (self.chat, self.user_input_and_submit) 

# %% ../nbs/06_chatbot.ipynb 10
class ChatBot(ChatBotView):

    def __init__(self, model):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()
        self.submit_button.on_click(self.on_click)
        self.model =model

    def on_click(self, change):
        self.chat.value = self.chat.value + "USER: " + self.user_input.value + '\n\n'
        self.user_input.value = ''
        ret = self.model.prompt(self.user_input.value)
        self.chat.value = self.chat.value +  "CHATBOT: "  + ret + '\n\n'

# %% ../nbs/06_chatbot.ipynb 12
class StudentChatBot(widgets.VBox):

    #user = traitlets.CUnicode()
    #response = traitlets.CUnicode()
    #step_by_step = traitlets.Bool()
    #metaphor = traitlets.Bool()
    #hints = traitlets.Bool()
    #guided_questions = traitlets.Bool() 
    
    def __init__(self, chatbot_model):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()

        self.chat_bot = ChatBot(chatbot_model)

        self.suggestion_buttons = HBox()
        self.step_by_step = widgets.Button(
            description='Step-by-Step',
            button_style='info',
            tooltip='Description',
        )
        self.metaphor = widgets.Button(
            description='Metaphor',
            button_style='info',
            tooltip='Description',
        )
        self.hints = widgets.Button(
            description='Hints',
            button_style='info',
            tooltip='Description',
        )
        self.guided_questions = widgets.Button(
            description='AI Guided Questions',
            button_style='info',
            tooltip='Description', 
        )
        self.suggestion_buttons.children = (self.step_by_step, self.metaphor, self.hints, self.guided_questions)
        self.children = (self.chat_bot, self.suggestion_buttons)

# %% ../nbs/06_chatbot.ipynb 14
class EducatorChatBot(widgets.VBox):

    #user = traitlets.CUnicode()
    #response = traitlets.CUnicode()
    #step_by_step = traitlets.Bool()
    #metaphor = traitlets.Bool()
    #hints = traitlets.Bool()
    #guided_questions = traitlets.Bool()  
    
    def __init__(self, chatbot_model):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()

        self.chat_bot = ChatBot(chatbot_model)

        self.suggestion_buttons = HBox()
        self.exam_questions = widgets.Button(
            description='Exam Questions',
            button_style='info',
            tooltip='Description',
        )
        self.lesson_plan = widgets.Button(
            description='Lesson Plan',
            button_style='info',
            tooltip='Description',
        )
        self.suggestion_buttons.children = (self.exam_questions, self.lesson_plan )
        self.children = (self.chat_bot, self.suggestion_buttons)
