# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_educator_model.ipynb.

# %% auto 0
__all__ = ['EducatorModel']

# %% ../nbs/07_educator_model.ipynb 2
import traitlets
from traitlets import HasTraits

# %% ../nbs/07_educator_model.ipynb 3
class EducatorModel(HasTraits):
    
    user = traitlets.CUnicode()
    response = traitlets.CUnicode()
    
    def __init__(self):
        super().__init__()

    def invoke(self, prompt):
        # Goal: use langchain invoke and use the return value to update the self.response variable
        self.response = "Hi am an AI and I have a response" # TODO: edit this line so the response comes from langchain
