# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_educator_profile.ipynb.

# %% auto 0
__all__ = ['EducatorProfileView']

# %% ../nbs/04_educator_profile.ipynb 1
from ipywidgets import VBox, HBox, HTML, Text, Button, Label
import ipyvuetify as v

# %% ../nbs/04_educator_profile.ipynb 2
class EducatorProfileView(VBox):

    def __init__(self):
        super().__init__()

        # Username input
    
        self.username_input = v.TextField(label='Name:', placeholder='Enter your first and last name')

        # Eductor Level input
        self.key_input = v.Select(
    label='Educator Level',
    items=['Elementary School', 'Middle School', 'High School', 'College'])

         # Next button
        self.next_button = Button(description='Next')

         #Header
        self.header = v.Container(children=[
            v.Html(
                tag='h1',
                attributes={'title': 'a title'},
                children=['Educator User Profile']
            )
        ])


        # Arrange widgets vertically
        self.children = [
            self.header,  # Heading
            self.username_input,       # Username label and input box
            self.key_input,       # Password label and input box
            HBox([self.next_button], layout={'justify_content': 'flex-end'}),  # Login button aligned to the right
        ]
