# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_madlib.ipynb.

# %% auto 0
__all__ = ['MadLibModel', 'MadLibView']

# %% ../nbs/05_madlib.ipynb 1
import ipywidgets as widgets
import traitlets
from ipywidgets import Textarea, Text, Layout, HBox, Stack, Layout
from traitlets import HasTraits
import os

# %% ../nbs/05_madlib.ipynb 2
class MadLibModel(object):

    def __init__(self, description, variables, template, **kwargs):
        
        self.description = description
        # two ways to save variables... 
        for key, value in variables.items(): # ... as attributes
            setattr(self, key, value)
        self.variables = variables # ...or as a dictionary, ex. { 'input_text': 'value' }  
        self.template = template # string: '{input_text}'


# %% ../nbs/05_madlib.ipynb 5
class MadLibView(HBox):
    
    def __init__(self, model, **kwargs):
        super().__init__()
        
        self.model = model
        self.variables = {}
        for i, (key, value) in enumerate(self.model.variables.items()):
            text = Text(description=self.model.description, style={'description_width': 'initial'})
            self.variables[key] = text

        self.submit_button = widgets.Button(
            value=False,
            disabled=False,
            button_style='success',
            icon='arrow-circle-right' 
        )
        self.children = list(self.variables.values()) 
