# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_student_profile.ipynb.

# %% auto 0
__all__ = ['StudentProfile']

# %% ../nbs/12_student_profile.ipynb 1
import ipywidgets as widgets
from ipywidgets import VBox, HTML, HBox, Label, Tab, Output, Button, Text, Textarea
from IPython.display import display, clear_output
import ipyvuetify as v

# %% ../nbs/12_student_profile.ipynb 2
class StudentProfile(widgets.VBox):
    
    def __init__(self):
        super().__init__()

        
        # Username input
        self.username_label = Label('Name/ID:')
        self.username_input = Text(placeholder='Enter your name')
        
        # School input
        self.school_label = Label('School/College:')
        self.school_input = Text(placeholder='Enter Your School', password=True)

        # Year input
        self.year_label = Label('Enter your Grade Level:')
        self.year_input = v.Select(clearable=True, label='Grade Level', items=['Freshman', 'Sophomore', 'Junior', 'Senior'], value='')

        # Major input
        self.major_label = Label('Major:')
        self.major_input = Text(placeholder='Enter Your Major', password=True)

        # Minors/Certificates input
        self.minor_label = Label('Minors/Certificates:')
        self.minor_input = Text(placeholder='Enter Your Minors and/or Certificates', password=True)

        # Interests input
        self.interests_label = Label('List your outside interests:')
        self.interests_input = Textarea(placeholder='Enter your outside interests', password=True)

        
        # Next button
        self.next_button = Button(description='Next')
        
        # Arrange labels and inputs horizontally
        self.username_box = HBox([self.username_label, self.username_input])
        self.school_box = HBox([self.school_label, self.school_input])
        self.year_box = HBox([self.year_label, self.year_input])
        self.major_box = HBox([self.major_label, self.major_input])
        self.minor_box = HBox([self.minor_label, self.minor_input])
        self.interests_box = HBox([self.interests_label, self.interests_input])
        
        # Arrange widgets vertically
        self.children = [
            HTML('<h2>Student User Profile</h2>'),  # Heading
            self.username_box,       # Username label and input box
            self.school_box,       # Password label and input box
            self.year_box,
            self.major_box,
            self.minor_box,
            self.interests_box,
            HBox([self.next_button], layout={'justify_content': 'flex-end'}),  # Login button aligned to the right
        ]
