# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_student_profile.ipynb.

# %% auto 0
__all__ = ['StudentProfile']

# %% ../nbs/12_student_profile.ipynb 1
import ipywidgets as widgets
from ipywidgets import VBox, HTML, HBox, Label, Tab, Output, Button, Text, Textarea
from IPython.display import display, clear_output
import ipyvuetify as v

# %% ../nbs/12_student_profile.ipynb 2
class StudentProfile(widgets.VBox):
    
    def __init__(self):
        super().__init__()

        
        # Username input
        self.username_input = v.TextField(label='Name:', placeholder='Enter username')

        
        # School input
        self.school_input = v.TextField(label='School:', placeholder='Enter your school')

        # Year input
        self.year_input = v.Select(clearable=True, label='Grade Level', items=['Freshman', 'Sophomore', 'Junior', 'Senior'], value='')

        # Major input
        self.major_input = v.TextField(label='Major:', placeholder='Enter your major')

        # Minors/Certificates input
        self.minor_input = v.TextField(label='Minors/Certificates:', placeholder='Enter your minors and/or certificates')

        # Interests input
        self.interests_input = v.TextField(label='Outside Interests:', placeholder='Enter your outside interests')

        
   
        # Next button
        self.next_button = Button(description='Next')


        #Header
        self.header = v.Container(children=[
            v.Html(
                tag='h1',
                attributes={'title': 'a title'},
                children=['Student Profile']
            ),

            v.Icon(children=['mdi-account'])


        ])

   # Arrange widgets vertically
        self.children = [
            self.header, # Heading 
            self.username_input,       # Username label and input box
            self.school_input,       # Password label and input box
            self.year_input,
            self.major_input,
            self.minor_input,
            self.interests_input,
            HBox([self.next_button], layout={'justify_content': 'flex-end'}),  # Login button aligned to the right
        ]
