# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_student_course_overview.ipynb.

# %% auto 0
__all__ = ['StudentCourseOverview']

# %% ../nbs/14_student_course_overview.ipynb 1
from .file_viewer import FileViewer
import ipywidgets as widgets
from ipywidgets import VBox, HBox, HTML, Button, Label, Text, Checkbox, Accordion, FileUpload
from IPython.display import display, clear_output
import ipyvuetify as v
from traitlets import observe

# %% ../nbs/14_student_course_overview.ipynb 2
class StudentCourseOverview(VBox):
    
    def __init__(self, file_viewer):
        super().__init__()

        # File Upload button
        self.file_upload = FileUpload(accept='', multiple=False)
        self.file_upload_button = Button(description='Upload')

        # global file viewer (that has model)
        self.file_viewer = file_viewer
        
        # Course overview text
        self.course_overview_label = Label('Course Overview:')
        self.course_overview_text = Text(placeholder='Enter course overview')
        
        # AI Guidelines text
        self.ai_guidelines_label = Label('AI Guidelines:')
      
        
        # Binary features checkboxes
        self.step_by_step_checkbox = Checkbox(description='Step-by-Step')
        self.metaphor_checkbox = Checkbox(description='Metaphor')
        self.hints_checkbox = Checkbox(description='Hints')
        self.ai_guided_questions_checkbox = Checkbox(description='AI Guided Questions')
        
        
        # Open-ended response textbox
        self.open_ended_label = Label('Open-ended Response:')
        self.open_ended_text = Text(placeholder='Enter open-ended response')

        # Next button
        self.next_button = Button(description='Next')
        
        # Arrange widgets vertically
        self.children = [
            HTML('<h2>Course Overview</h2>'),  # Heading
            HBox([self.file_upload, self.file_upload_button]),  # File upload button
            self.file_viewer,
            self.course_overview_label, self.course_overview_text,  # Course overview
            self.ai_guidelines_label,   # AI Guidelines
            VBox([self.step_by_step_checkbox, self.metaphor_checkbox,
                  self.hints_checkbox, self.ai_guided_questions_checkbox]),  # Binary features checkboxes
            self.open_ended_label, self.open_ended_text,  # Open-ended response
            HBox([self.next_button], layout={'justify_content': 'flex-end'}), 
        ]
