# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_student_course_overview.ipynb.

# %% auto 0
__all__ = ['StudentCourseOverview']

# %% ../nbs/14_student_course_overview.ipynb 1
from .file_viewer import FileViewer
import ipywidgets as widgets
from ipywidgets import VBox, HBox, HTML, Button, Label, Text, Checkbox, Accordion, FileUpload
from IPython.display import display, clear_output
import ipyvuetify as v
from traitlets import observe

# %% ../nbs/14_student_course_overview.ipynb 2
class StudentCourseOverview(VBox):
    def __init__(self, file_viewer):
        super().__init__()
        # global file viewer (that has model)
        self.file_viewer = file_viewer
        # Course overview text
        self.course_overview_label = Label('Course Overview:')
        # self.course_overview_text = Text(placeholder=‘Enter course overview’)
        # Next button
        self.next_button = Button(description='Next')
        # Arrange widgets vertically
        self.children = [
            HTML('<h2>Course Overview</h2>'),  # Heading
            self.file_viewer,
            self.course_overview_label,  # Course overview
            HBox([self.next_button], layout={'justify_content': 'flex-end'}),
        ]
