# AUTOGENERATED! DO NOT EDIT! File to edit: ../thirdTab.ipynb.

# %% auto 0
__all__ = ['ThirdTab']

# %% ../thirdTab.ipynb 1
import ipywidgets as widgets
from ipywidgets import Tab, Output, Button


# %% ../thirdTab.ipynb 2
class ThirdTab(widgets.VBox):
    
    def __init__(self):
        # If you forget to call the superconstructor on an extended widget
        # you will get an AttributeError: object has no attribute '_model_id'
        super().__init__()
        
        # Using Accordion
        # Create accordion containing HTML content
        self.using_acc = widgets.Accordion()
        # self.using_acc.set_title(0, 'Using this App')
        USING_TEXT = '''
            In the Data tab above, you can review the dataset.
            In the Selection tab, you can search for and download data of interest.
            Once you've selected data, generate plots in the Visualize tab.
            '''
        self.using_body = widgets.HTML(USING_TEXT)
        self.using_acc.children = (self.using_body, )
        
        # Data Souces Accordion
        # Create accordion containing HTML content
        self.sources_acc = widgets.Accordion()
       # self.sources_acc.set_title(0, 'Data Sources')
        SOURCES_TEXT = '''
            Land-Ocean Temperature Index
            Global Temperature (NASA)
            ,
            GISS Surface Temperature Analysis (NASA)
            
            This site is based on data downloaded from the following site on 2020-07-14:
            Global Mean Estimates based on Land_and Ocean Data (NASA)
            '''
        self.sources_body = widgets.HTML(SOURCES_TEXT)
        self.sources_acc.children = (self.sources_body, )
        
        self.next_button = Button(description='Next')
        
        self.children = (self.using_acc, self.sources_acc, self.next_button)
     
